### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by yael-lorenzo** [athena-oss/plugin-gradle#5]
`$athena new-issue`

**Athena Environment**
OS: Darwin asset682.local 15.6.0 Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64
Athena version: 0.10.3
Plugins:
 - appium [0.3.0]
 - avd [0.4.0]
 - base [0.10.3]
 - doctrine [1.0.0]
 - gradle [0.3.0]
 - java [1.0.0]
 - php [0.7.4]
 - proxy [0.3.1]
Images:
 - olx/athena-doctrine [1.0.0] 7e11852b270b
 - olx/athena-gradle-java-openjdk-latest-my-android [1.0.0] 89da4b2da77c
 - olx/athena-gradle-java-openjdk-latest [1.0.0] 89da4b2da77c
 - olx/athena-php7.0-php-php7.0 [1.0.0] ee69fed61e7e
 - olx/athena-appium [0.3.0] 443acf500a9b
 - olx/athena-avd-nexus-one-api-24 [0.4.0] ecbba13c11aa
 - olx/athena-gradle-android-java7-avd [1.0.0] 73030631545f
 - olx/athena-php5.6-php-php5.6 [1.0.0] 4817c146a321
 - olx/athena-proxy [0.3.1] 19d13d9bc0f9
Running containers:

The result

`$ athena gradle exec /Users/yael.lorenzo/git/athena-plugin-java/mnt/test-reports -PmainClass=BddProcessor execute --skip-sync`

[DEBUG] Skipped auto link with appium 'athena-plugin-appium-0'. Container is not running.
[DEBUG] Skipped auto link with Selenium. Plugin is not installed...
[DEBUG] using container with default router
[DEBUG] starting container athena-plugin-gradle-java-openjdk-latest-0 for command 'exec' ...
docker: Error response from daemon: create  athena_cache_android: " athena_cache_android" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.

This didnt not happened here

**Athena Environment**
```
OS: Darwin asset682.local 15.6.0 Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64
Athena version: 0.10.1
Plugins:
 - base [0.10.1]
 - gradle [0.3.0]
 - php [0.7.2]
Images:
 - olx/athena-doctrine [1.0.0] 7e11852b270b
 - olx/athena-gradle-java-openjdk-latest-my-android [1.0.0] 89da4b2da77c
 - olx/athena-gradle-java-openjdk-latest [1.0.0] 89da4b2da77c
 - olx/athena-php7.0-php-php7.0 [1.0.0] ee69fed61e7e
 - olx/athena-appium [0.3.0] 443acf500a9b
 - olx/athena-avd-nexus-one-api-24 [0.4.0] ecbba13c11aa
 - olx/athena-gradle-android-java7-avd [1.0.0] 73030631545f
 - olx/athena-php5.6-php-php5.6 [1.0.0] 4817c146a321
 - olx/athena-proxy [0.3.1] 19d13d9bc0f9
Running containers:
```

**Comment by yael-lorenzo** [comment]
@caiomoritz @pproenca could you please take a look ?

**Comment by yael-lorenzo** [comment]
This is the reason https://github.com/athena-oss/athena/pull/40

**Comment by ghost** [comment]
@yael-lorenzo-olx could you please update the description with the command you executed? I see the output starting with `[DEBUG]` but can't tell where it came from.

**Comment by yael-lorenzo** [comment]
I ran `athena gradle exec /Users/yael.lorenzo/git/athena-plugin-java/mnt/test-reports -PmainClass=BddProcessor execute --skip-sync`

**Comment by pproenca** [comment]
Hey @yael-lorenzo-olx can you please try with the latest changes from the gradle plugin master?

The plugin now also requires Athena v0.10.4

**Comment by yael-lorenzo** [comment]
Hey @pproenca this is currently working. Thanks a lot!
